import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="h-full">
            <body className={cn('relative h-full font-sans antialiased', inter.className)}>
                <main className="relative h-full font-sans min-h-screen">
                    <Navbar />
                    <div className="flex-grow flex-1">{children}</div>
                </main>
            </body>
        </html>
    );
}
